spring.application.name=restful-web-services
#spring.mvc.apiversion.use.path-segment=0 
#e.g ==> http://localhost:8080/2/sbiname


########Below versioning can be used only one at a time ######################

#spring.mvc.apiversion.use.query-parameter=version 
#e.g. ==> http://localhost:8080/sbiname?version=1

#spring.mvc.apiversion.use.header=X-API-VERSION 
#e.g ==>http://localhost:8080/namesbi with headers X-API-VERSION 1 or 2.

spring.mvc.apiversion.use.media-type-parameter[application/json]=version
#e.g ==> http://localhost:8080/namesbi with accept as application/json;version=1

#This is for all function of actuators
management.endpoints.web.exposure.include=*

# This is to enable H2 DB
spring.h2.console.enabled=true

#This is to set datasource DB url
spring.datasource.url=jdbc:h2:mem:testDB

#This is to prevent initialization of data on server start.
spring.jpa.defer-datasource-initialization=true

#Print all sql queries in console
spring.jpa.show-sql=true

#Set username and password for spring security
spring.security.user.name=user
spring.security.user.password=password